name: Deploy Solution react-slick
on:
  workflow_dispatch:
    inputs:
      purpose:
        description: "purpose of run"
        default: ""
        required: true
        type: string
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**.yml"

permissions:
  # req: Azure login for user-defined managed identity
  id-token: write
  # req: Azure login for user-defined managed identity
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.16.0
      - name: Run npm ci
        run: npm ci
      - name: Bundle Heft & Package
        run: |
          npm run build
      - name: CLI for Microsoft 365 Login
        uses: pnp/action-cli-login@v4.0.0
        with:
          APP_ID: ${{ secrets.M365_CICD_APP_CLIENTID }}
          TENANT: ${{ secrets.TENANT_ID }}
      - name: CLI for Microsoft 365 Deploy App
        uses: pnp/action-cli-deploy@v6.0.0
        with:
          APP_FILE_PATH: sharepoint/solution/${{ vars.PKG_NAME }}.sppkg
          SKIP_FEATURE_DEPLOYMENT: false
          OVERWRITE: true
          SCOPE: sitecollection
          SITE_COLLECTION_URL: ${{ vars.APP_SITE_CATALOG }}
